package com.cm.entities;
// Generated Mar 1, 2017 1:55:47 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Accounts generated by hbm2java
 */
@Entity
@Table(name = "accounts", catalog = "cm")
public class AccountEntity implements java.io.Serializable {

	private Long userId;
	private String username;
	private String password;
	private String nameOfCustomer;
	private Date birthdate;
	private String role;
	private Boolean isActive;
	private Set<TicketEntity> tickets = new HashSet<TicketEntity>(0);
	private Set<MovieEntity> movies = new HashSet<MovieEntity>(0);

	public AccountEntity() {
	}

	public AccountEntity(String username, String password, String nameOfCustomer, Date birthdate, String role,
			Boolean isActive, Set<TicketEntity> tickets, Set<MovieEntity> movies) {
		this.username = username;
		this.password = password;
		this.nameOfCustomer = nameOfCustomer;
		this.birthdate = birthdate;
		this.role = role;
		this.isActive = isActive;
		this.tickets = tickets;
		this.movies = movies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "userId", unique = true, nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "nameOfCustomer", length = 128)
	public String getNameOfCustomer() {
		return this.nameOfCustomer;
	}

	public void setNameOfCustomer(String nameOfCustomer) {
		this.nameOfCustomer = nameOfCustomer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthdate", length = 10)
	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	@Column(name = "role", length = 30)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "isActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accounts")
	public Set<TicketEntity> getTickets() {
		return this.tickets;
	}

	public void setTickets(Set<TicketEntity> tickets) {
		this.tickets = tickets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accounts")
	public Set<MovieEntity> getMovies() {
		return this.movies;
	}

	public void setMovies(Set<MovieEntity> movies) {
		this.movies = movies;
	}

}
