package com.cm.entities;
// Generated Mar 1, 2017 2:04:33 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "ticket", catalog = "cm")
public class TicketEntity implements java.io.Serializable {

	private Long ticketId;
	private AccountEntity accounts;
	private SeatEntity seat;
	private String username;
	private String phone;
	private Long price;

	public TicketEntity() {
	}

	public TicketEntity(AccountEntity accounts, SeatEntity seat, String username, String phone, Long price) {
		this.accounts = accounts;
		this.seat = seat;
		this.username = username;
		this.phone = phone;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ticketId", unique = true, nullable = false)
	public Long getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(Long ticketId) {
		this.ticketId = ticketId;
	}
	
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public AccountEntity getAccounts() {
		return this.accounts;
	}

	public void setAccounts(AccountEntity accounts) {
		this.accounts = accounts;
	}
	
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seatId")
	public SeatEntity getSeat() {
		return this.seat;
	}

	public void setSeat(SeatEntity seat) {
		this.seat = seat;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "phone", length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "price")
	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

}
