package com.cm.entities;
// Generated Feb 17, 2017 11:23:16 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Seat generated by hbm2java
 */
@Entity
@Table(name = "seat", catalog = "cm")
public class Seat implements java.io.Serializable {

	private long seatId;
	private Schedules schedules;
	private String seatName;
	private Boolean seatStatus;

	public Seat() {
	}

	public Seat(long seatId) {
		this.seatId = seatId;
	}

	public Seat(long seatId, Schedules schedules, String seatName, Boolean seatStatus) {
		this.seatId = seatId;
		this.schedules = schedules;
		this.seatName = seatName;
		this.seatStatus = seatStatus;
	}

	@Id

	@Column(name = "seatId", unique = true, nullable = false)
	public long getSeatId() {
		return this.seatId;
	}

	public void setSeatId(long seatId) {
		this.seatId = seatId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scheduleId")
	public Schedules getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Schedules schedules) {
		this.schedules = schedules;
	}

	@Column(name = "seatName", length = 4)
	public String getSeatName() {
		return this.seatName;
	}

	public void setSeatName(String seatName) {
		this.seatName = seatName;
	}

	@Column(name = "seatStatus")
	public Boolean getSeatStatus() {
		return this.seatStatus;
	}

	public void setSeatStatus(Boolean seatStatus) {
		this.seatStatus = seatStatus;
	}

}
