package com.fpt.entities;
// Generated Jan 18, 2017 7:34:38 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Accounts generated by hbm2java
 */
@Entity
@Table(name = "accounts", catalog = "cm")
public class Accounts implements java.io.Serializable {

	private int userId;
	private String username;
	private String password;
	private String role;
	private Set<Movie> movies = new HashSet<Movie>(0);

	public Accounts() {
	}

	public Accounts(int userId) {
		this.userId = userId;
	}

	public Accounts(int userId, String username, String password, String role, Set<Movie> movies) {
		this.userId = userId;
		this.username = username;
		this.password = password;
		this.role = role;
		this.movies = movies;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "role", length = 30)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accounts")
	public Set<Movie> getMovies() {
		return this.movies;
	}

	public void setMovies(Set<Movie> movies) {
		this.movies = movies;
	}

}
