package com.fpt.entities;
// Generated Jan 18, 2017 7:34:38 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "ticket", catalog = "cm")
public class Ticket implements java.io.Serializable {

	private Integer ticketId;
	private Schedules schedules;
	private Seat seat;
	private Double price;
	private String phone;
	private String email;
	private String nameOfCustomer;

	public Ticket() {
	}

	public Ticket(Schedules schedules, Seat seat, Double price, String phone, String email, String nameOfCustomer) {
		this.schedules = schedules;
		this.seat = seat;
		this.price = price;
		this.phone = phone;
		this.email = email;
		this.nameOfCustomer = nameOfCustomer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ticket_id", unique = true, nullable = false)
	public Integer getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(Integer ticketId) {
		this.ticketId = ticketId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "schedule_id")
	public Schedules getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Schedules schedules) {
		this.schedules = schedules;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seat_id")
	public Seat getSeat() {
		return this.seat;
	}

	public void setSeat(Seat seat) {
		this.seat = seat;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "name_of_customer", length = 50)
	public String getNameOfCustomer() {
		return this.nameOfCustomer;
	}

	public void setNameOfCustomer(String nameOfCustomer) {
		this.nameOfCustomer = nameOfCustomer;
	}

}
